
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.Map;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author arant
 */
public class CategoryChartPanel extends javax.swing.JPanel {

    /**
     * Creates new form CategoryChartPanel
     */
    private final Map<String, Integer> counts;
    private final Map<String, Double> percentages;

    public CategoryChartPanel(Map<String, Integer> counts, Map<String, Double> percentages) {
        this.counts = counts;
        this.percentages = percentages;
        setPreferredSize(new Dimension(500, counts.size() * 40));
        setBackground(Color.WHITE);
    }
    
    @Override
    public Dimension getPreferredSize() { // para ma full screen
        return new Dimension(getParent() != null ? getParent().getWidth() : 500, counts.size() * 50);
    }
    
    
    @Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2 = (Graphics2D) g;
    g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

    int y = 20;
    int maxWidth = getWidth() - 200;

    for (String category : counts.keySet()) {
        int count = counts.get(category);
        double percent = percentages.get(category);
        int barWidth = (int) (maxWidth * (percent / 100.0));

        // Draw bar
        g2.setColor(new Color(128, 0, 128)); // purple
        g2.fillRect(150, y, barWidth, 30);

        // Bold label for count + percent
        g2.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        g2.setColor(Color.BLACK);
        g2.drawString(count + " items (" + String.format("%.1f", percent) + "%)", 160 + barWidth, y + 20);

        // Category label (normal weight)
        g2.setFont(new Font("Segoe UI", Font.BOLD, 16));
        g2.drawString(category, 10, y + 20);

        y += 50;
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
